# Documentation: https://starship.rs/config/

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $git_status\
  $fill\
  $c\
  $cmake\
  $cobol\
  $daml\
  $dart\
  $deno\
  $dotnet\
  $elixir\
  $elm\
  $erlang\
  $fennel\
  $gleam\
  $golang\
  $guix_shell\
  $haskell\
  $haxe\
  $helm\
  $java\
  $julia\
  $kotlin\
  $gradle\
  ${custom.latex}\
  $lua\
  $nim\
  $nodejs\
  $ocaml\
  $opa\
  $perl\
  $php\
  $pulumi\
  $purescript\
  $python\
  $quarto\
  $raku\
  $rlang\
  $red\
  $ruby\
  $rust\
  $scala\
  $solidity\
  $swift\
  $terraform\
  $typst\
  $vlang\
  $vagrant\
  $zig\
  $cmd_duration\
  $time\
  $line_break\
  $character\
"""

command_timeout = 1000

[directory]
style = 'bright-blue'
before_repo_root_style = 'blue'
repo_root_style = 'bold bright-blue'
truncate_to_repo = false
truncation_symbol = '…/'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
symbol = ' '
style = '248'

[git_status]
format = """\
  [$conflicted](248)\
  [( $stashed)( $ahead_behind)](yellow)\
  [( $staged)](248)\
  [( $untracked)](green)\
  [( $modified)](blue)\
  [( $renamed)](248)\
  [( $deleted)](bright-red)\
"""
conflicted = '!'
staged = '$count='
untracked = '$count+'
modified = '$count*'
renamed = '$count~'
deleted = '$count-'
stashed = '≡'
ahead = '$count↑'
behind = '$count↓'
diverged = '$behind_count↓ $ahead_count↑'

[fill]
symbol = ' '

[cmd_duration]
format = ' [$duration]($style)'
style = '143'

[time]
disabled = false
format = ' [$time]($style) '
style = '109'

# Languages
[lua]
format = '[$symbol$version]($style) '
symbol = ' '
style = 'bright-blue'

[nodejs]
format = '[$symbol$version]($style) '
style = 'bright-green'

[php]
format = '[$symbol$version]($style) '
symbol = ' '
style = '147'

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
symbol = ' '
style = 'yellow'

[custom.latex]
command = "tex --version | head -n 1 | cut -d '(' -f 2 | cut -d ')' -f 1 | cut -d ' ' -f 2,3"
detect_extensions = ['tex', 'ltx', 'bib', 'sty', 'cls']
style = 'bright-blue'
symbol = ' '

